version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=blogadmin
      - POSTGRES_PASSWORD=blogadmin
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code/static
    links:
      - db
    depends_on:
      - db